### ISSUE TITLE
Acesso ao login e senha do administrador.

### ISSUE THREAD

**Issue by brunoliveira8** [lucascavalcante/rapadura-valley-mapa#1]
Cuidado que a senha e o login do administrador do site está amostra no documento include/db.php. Eu acessei o site http://www.rapaduravalley.org/mapa/ e consegui acessar a página do admnistrador.

**Comment by lucascavalcante** [comment]
Bruno, obrigado pelo aviso. Realmente foi uma falha grave que passou completamente despercebido.

**Comment by brunoliveira8** [comment]
Disponha :)
